// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Anhbman/microservice-server-cake/internal/controller"
	"github.com/Anhbman/microservice-server-cake/internal/service/cake"
	"github.com/Anhbman/microservice-server-cake/internal/service/user"
	"github.com/Anhbman/microservice-server-cake/internal/storage"
)

// Injectors from wire.go:

func InitializeApp() *controller.Controller {
	db := storage.InitDB()
	service := cake.NewService(db)
	userService := user.NewService(db)
	controllerController := controller.NewController(service, userService)
	return controllerController
}
